name: Replication 
on:
  - pull_request
  - push
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.9'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@latest
      - name: Instantiating the environment
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()' # precompiles the env
      - name: Theorem 3.6 - Adj A₂ > 0 in SL₃(ℤ) (for R=2) # (R=3 takes too long for CI)
        run: julia --project=@. scripts/SLnZ_AdjA2.jl -N 3 -R 2
      # - name: Theorem 3.10 - Adj_C₂ > 0 in Sp₄(ℤ) (R=3) # takes too long
      #   run: julia --project=@. scripts/Sp2nZ_AdjC2.jl -N 2 -R 3
      - name: Theorem 3.12 - Sp₄(ℤ) has property (T) (R=2)
        run: julia --project=@. scripts/Sp2nZ_has_T.jl -N 2 -R 2
      - name: Theorem 3.15 - Lev₂³ + Lev₃³ > 0 in Sp₆(ℤ) (R=2)
        run: julia --project=@. scripts/Sp2nZ_Level.jl -N 3 -R 2
      - name: Theorem 3.17 - G₂ has property (T) (R=2)
        run: julia --project=@. scripts/G2_has_T.jl -R 2
      - name: Theorem 3.18 - Adj_G₂ > 0 in G₂ (R=2 fails, R=3 takes too long for CI)
        # The theorem only states the positivity for R=3
        # This test only checks if the script runs property, see also the triple bounds notebook.
        run: julia --project=@. scripts/G2_Adj.jl -R 2

